local steamInventory = require("src.steam.inventory")
local localInventory = require("src.cosmetics.local_inventory")

---@class g.cosmetics
local cosmetics = {}


---------------------------------
--- Accessories/Customization ---
---------------------------------



---@class g.Avatar
---@field public avatar string Cat avatar ID
---@field public background string Background ID of the avatar
---@field public hat string? Cat hat ID



---@class g.CosmeticDef
---@field public image string?
---@field public upscale integer?
---@field public color objects.Color?
---@field public offsetX number? offset: how its positioned in pixels (e.g. hat is up)
---@field public offsetY number? offset: how its positioned in pixels (e.g. hat is up)
---@field public originX number? origin; affects scaling of image [0,1]
---@field public originY number? origin; affects scaling of image [0,1]
---@field public rarity integer? 0=Common, 1=Rare, 2=Legendary

---@alias g.CosmeticInfo.Type "HAT"|"BACKGROUND"|"AVATAR"

---@class g.CosmeticInfo: g.CosmeticDef
---@field public id string
---@field public type g.CosmeticInfo.Type
---@field public name string
---@field public image string
---@field public upscale integer
---@field public color objects.Color
---@field public offsetX number offset: how its positioned in pixels (e.g. hat is up)
---@field public offsetY number offset: how its positioned in pixels (e.g. hat is up)
---@field public originX number origin; affects scaling of image [0,1]
---@field public originY number origin; affects scaling of image [0,1]
---@field public rarity integer 0=Common, 1=Rare, 2=Legendary



---@type table<string, g.CosmeticInfo>
local COSMETIC_INFO = nil
---@type table<integer, string>|table<string, integer>
local STEAM_ITEMDEF_MAP = nil -- integer is steam itemdef id, string is cosmetic ID
local COSMETIC_UNLOCKS = objects.Set() --[[@as objects.Set<string>]]
local CHEST_COUNT = 0
---@type luasteam.uint64|nil
local CHEST_ITEMID = nil


---@param type g.CosmeticInfo.Type
---@param id string
---@param name string
---@param def g.CosmeticDef
local function defineCosmetic(type, id, name, def)
    ---@cast def g.CosmeticInfo
    def.type    = type
    def.id      = id
    def.name    = name

    def.image   = def.image   or id
    def.upscale = def.upscale or 1
    def.color   = def.color   or objects.Color.WHITE

    def.offsetX = def.offsetX or 0
    def.offsetY = def.offsetY or 0

    def.originX = def.originX or 0.5
    def.originY = def.originY or (type == "HAT") and 1 or 0.5
    -- originY=0.5 if normal, originY=1 if HAT.
    def.rarity  = def.rarity  or 0

    COSMETIC_INFO[id] = def
end


local ALWAYS_UNLOCKED = objects.Set() --[[@as objects.Set<string>]]
local function ensureLoaded()
    if COSMETIC_INFO then
        return
    end

    COSMETIC_INFO = {}
    defineCosmetic("AVATAR", "cat", "Regular Cat", {
        image = "happy_cat"
    })

    defineCosmetic("BACKGROUND", "white", "White", {
        image = "default_background",
    })
    ALWAYS_UNLOCKED:add("cat")
    ALWAYS_UNLOCKED:add("white")

    -- This loads the autogenerated cosmetics
    STEAM_ITEMDEF_MAP = love.filesystem.load("src/cosmetics/list.lua")()(defineCosmetic)
end

---@param id string
---@return boolean
local function isUnlocked(id)
    if ALWAYS_UNLOCKED:has(id) then
        return true
    end
    if consts.NO_STEAM then
        return localInventory.getUnlockedSet():has(id)
    end
    return COSMETIC_UNLOCKS:has(id)
end



---@return string[]
function cosmetics.getAll()
    ensureLoaded()
    local t = {}
    for k in pairs(COSMETIC_INFO) do
        t[#t+1] = k
    end
    return t
end

---@param id string cosmetic-info
---@return g.CosmeticInfo
function cosmetics.getInfo(id)
    ensureLoaded()
    helper.assert(COSMETIC_INFO[id], "cosmetic", id, "is not defined")
    return COSMETIC_INFO[id]
end



---@param id string cosmetic-info
---@return boolean
function cosmetics.isValidCosmetic(id)
    ensureLoaded()
    return (not not COSMETIC_INFO[id])
end



---@param typeFilter? "BACKGROUND"|"HAT"|"AVATAR"
---@return string[]
function cosmetics.getUnlocked(typeFilter)
    ensureLoaded()
    local t = {}
    for k,def in pairs(COSMETIC_INFO) do
        if isUnlocked(k) and ((not typeFilter) or typeFilter == def.type) then
            table.insert(t,k)
        end
    end
    return t
end



---Get all avatar cosmetic IDs
---@return string[]
function cosmetics.getAllAvatars()
    ensureLoaded()
    local t = {}
    for k, def in pairs(COSMETIC_INFO) do
        if def.type == "AVATAR" then
            table.insert(t, k)
        end
    end
    return t
end



---Get all hat cosmetic IDs
---@return string[]
function cosmetics.getAllHats()
    ensureLoaded()
    local t = {}
    for k, def in pairs(COSMETIC_INFO) do
        if def.type == "HAT" then
            table.insert(t, k)
        end
    end
    return t
end




---Avatar occupy 32x32 in size, with background.
---@param avatar g.Avatar
---@param x number
---@param y number
---@param drawBackground boolean?
---@param rot number?
---@param sx number?
---@param sy number?
---@param catDy number?
function cosmetics.drawAvatar(avatar, x, y, drawBackground, rot, sx,sy, catDy)
    ensureLoaded()
    local oy = 0
    sx = sx or 1
    sy = sy or sx
    rot = rot or 0
    catDy = catDy or 0

    -- Not 100% certain if this should be in g, but we can move it later.
    if drawBackground then
        local bginfo = cosmetics.getInfo(avatar.background)
        love.graphics.setColor(bginfo.color)
        g.drawImage(bginfo.image, x, y, 0, sx * bginfo.upscale, sy)
        -- When drawing with background, assume it's for rendering in UI
        oy = math.floor((consts.AVATAR_SIZE - 16) / 2) - 1
    end

    love.graphics.setColor(1, 1, 1)
    local catinfo = cosmetics.getInfo(avatar.avatar)
    g.drawImage(catinfo.image, x, y + (oy + catDy) * sy, 0, sx,sy)

    if avatar.hat then
        local hatinfo = cosmetics.getInfo(avatar.hat)
        local s = hatinfo.upscale or 1
        love.graphics.setColor(hatinfo.color)
        -- Note: This assume cat avatar is 16x16. If not, make this configurable.
        g.drawImageOffset(
            hatinfo.image,
            x + (hatinfo.offsetX) * s,
            y + (hatinfo.offsetY + oy + catDy - 8) * s * sy,
            0, sx*s, sy*s,
            hatinfo.originX,
            hatinfo.originY
        )
    end
end

---@param x number
---@param y number
---@param scale number?
---@param drawBackground boolean?
---@param drawBobbing boolean?
function cosmetics.drawPlayerAvatar(x, y, scale, drawBackground, drawBobbing)
    ensureLoaded()
    local dy = 0
    if drawBobbing then
        local t = (love.timer.getTime() * 2 + 10) % (2 * math.pi)
        dy = math.sin(t)/2-1
    end
    return cosmetics.drawAvatar(
        g.getSn().avatar, x, y,
        drawBackground,
        0,
        scale, scale,
        dy
    )
end


function cosmetics.init()
    ensureLoaded()
    localInventory.init(cosmetics.isValidCosmetic)

    local luasteam = Steam.getSteam()
    if luasteam then
        -- Try refresh
        cosmetics.tryRefresh()
    end

    -- Load cached cosmetics unlocks
    if love.filesystem.getInfo("cosmeticcache.json", "file") then
        local read = love.filesystem.read("cosmeticcache.json")
        if read then
            local ok, jsondata = pcall(json.decode, read)
            if ok then
                for _, cosmeticid in ipairs(jsondata) do
                    COSMETIC_UNLOCKS:add(cosmeticid)
                end
            end
        end
    end
end


function cosmetics.tryRefresh()
    ensureLoaded()

    local luasteam = Steam.getSteam()
    if luasteam then
        steamInventory.getAllItems(function(result, handle)
            if result == "OK" then
                local items = luasteam.inventory.getResultItems(handle)
                COSMETIC_UNLOCKS:clear()

                if items then
                    for _, item in ipairs(items) do
                        if item.definition == consts.STEAM_CHEST_ITEMDEFID then
                            CHEST_COUNT = item.quantity
                            CHEST_ITEMID = item.id
                        elseif STEAM_ITEMDEF_MAP[item.definition] then
                            COSMETIC_UNLOCKS:add(STEAM_ITEMDEF_MAP[item.definition])
                        end
                    end
                end

                -- Save cosmetics unlocks cache
                love.filesystem.write("cosmeticcache.json", json.encode(COSMETIC_UNLOCKS:totable()))
            end
        end)
    end
end


function cosmetics.getChestCount()
    if consts.NO_STEAM then
        return localInventory.getChestCount()
    end

    return CHEST_ITEMID and CHEST_COUNT or 0
end

---@return string?
local function pickLockedLocalCosmetic()
    local candidates = {}
    local localUnlocks = localInventory.getUnlockedSet()
    for id in pairs(COSMETIC_INFO) do
        if not ALWAYS_UNLOCKED:has(id) and not localUnlocks:has(id) then
            candidates[#candidates+1] = id
        end
    end

    if #candidates <= 0 then
        return nil
    end

    return helper.randomChoice(candidates)
end


---Open one cosmetic chest.
---@param callback fun(success:boolean, cosmetic:string?) The unlocked cosmetic ID is passed or nil on failure.
function cosmetics.openChest(callback)
    if cosmetics.getChestCount() <= 0 then
        return callback(false)
    end

    local luasteam = Steam.getSteam()
    if consts.NO_STEAM then
        local cosmeticId = pickLockedLocalCosmetic()
        if cosmeticId and localInventory.consumeChestForUnlock(cosmeticId) then
            return callback(true, cosmeticId)
        end

        return callback(false)
    end

    if not luasteam then
        return callback(false)
    end

    steamInventory.exchangeItems(consts.STEAM_CHEST_GENERATOR_ITEMDEFID, {[CHEST_ITEMID] = 1}, function(result, handle)
        if result == "OK" then
            CHEST_COUNT = CHEST_COUNT - 1
            local items = luasteam.inventory.getResultItems(handle)

            if items then
                for _, item in ipairs(items) do
                    if item.definition == consts.STEAM_CHEST_ITEMDEFID then
                        CHEST_COUNT = item.quantity
                        CHEST_ITEMID = item.id
                    elseif STEAM_ITEMDEF_MAP[item.definition] then
                        COSMETIC_UNLOCKS:add(STEAM_ITEMDEF_MAP[item.definition])
                        callback(true, STEAM_ITEMDEF_MAP[item.definition])
                    end
                end
            end
        end
    end)
end



return cosmetics
